#!/bin/sh
HERE="$(dirname "$(readlink -f "$0")")"

export PATH="${HERE}/usr/bin:${PATH}"
export LD_LIBRARY_PATH="${HERE}/usr/lib:${LD_LIBRARY_PATH}"
export OPENCV_PLUGIN_PATH="${HERE}/usr/lib/opencv4"

cd "${HERE}/usr/share/wifi-video-receiver" || exit 1
exec "${HERE}/usr/bin/WiFiVideoReceiver" "$@"
